In [1]:
from vilt.transforms import pixelbert_transform
from vilt.datamodules.datamodule_base import get_pretrained_tokenizer

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
import requests
from PIL import Image
import io

In [5]:
from torchvision.transforms import ToTensor

In [6]:
torch.__version__

'1.10.0'

In [7]:
transform = pixelbert_transform()

384 639


In [36]:
scripted_pb_transform = torch.jit.script(pixelbert_transform(384))

384 639


In [37]:
url = "https://media.istockphoto.com/photos/joyful-dog-playing-with-whip-while-walking-on-green-field-picture-id1187003477?k=20&m=1187003477&s=612x612&w=0&h=fvUFuwvTZWEJjk8HUU80-zvaI4gg9szPGJ2RdASH72s="
text = "How many dogs are there in this picture?"
res = requests.get(url)
image = Image.open(io.BytesIO(res.content)).convert("RGB")

In [38]:
pil_to_tensor = ToTensor()(image).unsqueeze_(0)

In [39]:
pil_to_tensor.shape

torch.Size([1, 3, 408, 612])

In [40]:
output = scripted_pb_transform(pil_to_tensor)

In [41]:
output.shape

torch.Size([1, 3, 384, 576])

In [28]:
transform(pil_to_tensor).numpy()

array([[[[ 0.96862745,  0.96862733,  0.9686276 , ...,  0.9840715 ,
           0.9843137 ,  0.9843136 ],
         [ 0.96862733,  0.9686272 ,  0.96862745, ...,  0.9840715 ,
           0.98431396,  0.98431385],
         [ 0.9686276 ,  0.96862745,  0.9686277 , ...,  0.9840715 ,
           0.98431385,  0.98431385],
         ...,
         [-0.20907253, -0.18830395, -0.1918391 , ..., -0.6707498 ,
          -0.6691296 , -0.6904973 ],
         [-0.18646789, -0.1597532 , -0.13315493, ..., -0.63559294,
          -0.619908  , -0.6589998 ],
         [-0.16844904, -0.14115906, -0.10167593, ..., -0.58494806,
          -0.5677389 , -0.6080045 ]],

        [[ 0.8980392 ,  0.8980391 ,  0.8980391 , ...,  0.9765917 ,
           0.9764706 ,  0.9764705 ],
         [ 0.8980391 ,  0.898039  ,  0.898039  , ...,  0.9765917 ,
           0.9764707 ,  0.9764706 ],
         [ 0.8980391 ,  0.8980391 ,  0.8980391 , ...,  0.9765918 ,
           0.9764706 ,  0.9764706 ],
         ...,
         [-0.01767218,  0.00528944

In [15]:
from torch.utils.mobile_optimizer import optimize_for_mobile

In [16]:
optimized_torchscript_processor = optimize_for_mobile(scripted_pb_transform)

In [17]:
optimized_torchscript_processor._save_for_lite_interpreter("vilt_lite_processor.ptl")

# For reference

In [18]:
base = np.load("joyful_dog_pixelbert_og.npy")

In [19]:
base.shape

(1, 3, 384, 576)

In [20]:
base

array([[[[ 0.96862745,  0.96862745,  0.96862745, ...,  0.9843137 ,
           0.9843137 ,  0.9843137 ],
         [ 0.96862745,  0.96862745,  0.96862745, ...,  0.9843137 ,
           0.9843137 ,  0.9843137 ],
         [ 0.96862745,  0.96862745,  0.96862745, ...,  0.9843137 ,
           0.9843137 ,  0.9843137 ],
         ...,
         [-0.20784312, -0.18431371, -0.19215685, ..., -0.6627451 ,
          -0.67058825, -0.6862745 ],
         [-0.18431371, -0.1607843 , -0.1372549 , ..., -0.6313726 ,
          -0.62352943, -0.654902  ],
         [-0.16862744, -0.14509803, -0.10588235, ..., -0.58431375,
          -0.5686275 , -0.60784316]],

        [[ 0.8980392 ,  0.8980392 ,  0.8980392 , ...,  0.9764706 ,
           0.9764706 ,  0.9764706 ],
         [ 0.8980392 ,  0.8980392 ,  0.8980392 , ...,  0.9764706 ,
           0.9764706 ,  0.9764706 ],
         [ 0.8980392 ,  0.8980392 ,  0.8980392 , ...,  0.9764706 ,
           0.9764706 ,  0.9764706 ],
         ...,
         [-0.01960784,  0.00392163

In [21]:
output

tensor([[[[ 0.9686,  0.9686,  0.9686,  ...,  0.9841,  0.9843,  0.9843],
          [ 0.9686,  0.9686,  0.9686,  ...,  0.9841,  0.9843,  0.9843],
          [ 0.9686,  0.9686,  0.9686,  ...,  0.9841,  0.9843,  0.9843],
          ...,
          [-0.2091, -0.1883, -0.1918,  ..., -0.6707, -0.6691, -0.6905],
          [-0.1865, -0.1598, -0.1332,  ..., -0.6356, -0.6199, -0.6590],
          [-0.1684, -0.1412, -0.1017,  ..., -0.5849, -0.5677, -0.6080]],

         [[ 0.8980,  0.8980,  0.8980,  ...,  0.9766,  0.9765,  0.9765],
          [ 0.8980,  0.8980,  0.8980,  ...,  0.9766,  0.9765,  0.9765],
          [ 0.8980,  0.8980,  0.8980,  ...,  0.9766,  0.9765,  0.9765],
          ...,
          [-0.0177,  0.0053,  0.0164,  ..., -0.5454, -0.5436, -0.5650],
          [-0.0328,  0.0083,  0.0385,  ..., -0.5107, -0.4944, -0.5335],
          [-0.0419,  0.0095,  0.0484,  ..., -0.4601, -0.4422, -0.4825]],

         [[ 0.8431,  0.8431,  0.8431,  ...,  0.9451,  0.9451,  0.9451],
          [ 0.8431,  0.8431,  

In [42]:
output = output.numpy()

In [43]:
np.mean(np.abs(output - base))

0.0033902633